name: Update README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: npm install
    - run: npm run update-readme
      env:
        TOKEN: ${{ secrets.JESUVILORIA_SECRET }}
    - run: |
        git config user.name jesuviloria
        git config user.email jesudvm12@example.com
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/jesuviloria/jesuviloria.git
        git add README.md
        git commit -m "[bot] Update README with latest info"
        git push origin main
